from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Mapping, MutableMapping


ALLOWED_SOURCE_STATUS = {"VERIFIED", "USER_PROVIDED", "TODO_VERIFY"}
EXPECTED_COMPANIES = {"한화생명", "한화투자증권", "한화자산운용"}

# Exposure lists that must exist and carry at least one entry.
REQUIRED_EXPOSURE_LISTS = ("transmission_paths", "key_metrics", "watchpoints")
# Directional lists: either one may be empty (a clearly one-sided exposure), but
# not both — an exposure with no factor at all cannot explain company impact.
DIRECTIONAL_EXPOSURE_LISTS = ("positive_factors", "negative_factors")
# Fields the Company Profile owns. The LLM never produces these; they are copied
# onto the analysis result so cached and live paths share one source of truth.
PROFILE_INJECTED_FIELDS = (
    "relevance",
    "direction",
    "positive_factors",
    "negative_factors",
    "key_metrics",
    "watchpoints",
    "source_status",
)
_UPPERCASE_INJECTED_FIELDS = {"relevance", "direction"}


def _load_yaml_compatible(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        try:
            from omegaconf import OmegaConf
        except ImportError as exc:
            raise RuntimeError(
                f"{path} is YAML rather than JSON-compatible YAML; install omegaconf"
            ) from exc
        payload = OmegaConf.to_container(OmegaConf.load(path), resolve=True)
    if not isinstance(payload, dict):
        raise ValueError(f"Company profile must be an object: {path}")
    return payload


def _validate_profile(profile: dict[str, Any], path: Path) -> dict[str, Any]:
    company = str(profile.get("company", "")).strip()
    business_type = str(profile.get("business_type", "")).strip()
    exposures = profile.get("market_exposures")
    if not company or not business_type or not isinstance(exposures, dict):
        raise ValueError(f"Invalid company profile structure: {path}")
    for category, exposure in exposures.items():
        if not isinstance(exposure, dict):
            raise ValueError(f"Invalid exposure {category}: {path}")
        status = exposure.get("source_status")
        if status not in ALLOWED_SOURCE_STATUS:
            raise ValueError(f"Invalid source_status for {company}/{category}: {status}")
        for field in REQUIRED_EXPOSURE_LISTS:
            value = exposure.get(field)
            if not isinstance(value, list) or not value:
                raise ValueError(f"{field} must be a non-empty list for {company}/{category}: {path}")
        for field in DIRECTIONAL_EXPOSURE_LISTS:
            if not isinstance(exposure.get(field), list):
                raise ValueError(f"{field} must be a list for {company}/{category}: {path}")
        if not any(exposure[field] for field in DIRECTIONAL_EXPOSURE_LISTS):
            raise ValueError(
                f"At least one of positive_factors/negative_factors is required for {company}/{category}"
            )
    return profile


def load_company_profiles(profile_dir: str | Path) -> dict[str, dict[str, Any]]:
    root = Path(profile_dir)
    if not root.is_dir():
        raise FileNotFoundError(f"Profile directory not found: {root}")
    profiles: dict[str, dict[str, Any]] = {}
    for path in sorted(root.glob("*.yaml")):
        profile = _validate_profile(_load_yaml_compatible(path), path)
        company = profile["company"]
        if company in profiles:
            raise ValueError(f"Duplicate company profile: {company}")
        profiles[company] = profile
    missing = EXPECTED_COMPANIES - profiles.keys()
    if missing:
        raise ValueError(f"Missing required company profiles: {sorted(missing)}")
    return profiles


def exposure_for(
    profiles: Mapping[str, Mapping[str, Any]],
    company: str,
    category: str | None,
) -> dict[str, Any]:
    """Return the market exposure a company profile declares for one signal category."""
    if not category:
        return {}
    profile = profiles.get(company)
    if not isinstance(profile, Mapping):
        return {}
    exposures = profile.get("market_exposures")
    if not isinstance(exposures, Mapping):
        return {}
    exposure = exposures.get(category)
    return dict(exposure) if isinstance(exposure, Mapping) else {}


def apply_profile_exposure(
    companies: MutableMapping[str, MutableMapping[str, Any]],
    profiles: Mapping[str, Mapping[str, Any]],
    category: str | None,
) -> MutableMapping[str, MutableMapping[str, Any]]:
    """Inject Profile-owned exposure fields into per-company analysis blocks.

    relevance and direction are never generated by the LLM: they are read from the
    Company Profile and written here so the cached and live paths end up with the
    same final schema. Companies without a matching exposure keep their values.
    """
    for company, impact in companies.items():
        exposure = exposure_for(profiles, company, category)
        if not exposure:
            continue
        for field in PROFILE_INJECTED_FIELDS:
            if field not in exposure:
                continue
            value = exposure[field]
            if field in _UPPERCASE_INJECTED_FIELDS:
                impact[field] = str(value).strip().upper()
            elif isinstance(value, list):
                impact[field] = list(value)
            else:
                impact[field] = value
    return companies
